name: Lint

on:
  push:
  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install cmake & configuration dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang clang-tidy cmake ninja-build libc++-dev libc++abi-dev

      - name: Configure
        run: |
          cmake --preset debug-clang \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run clang-tidy
        run: |
          run-clang-tidy -p build/debug/clang
